# Generated by Django 4.1.3 on 2022-12-29 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('words', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='references',
            old_name='reference',
            new_name='referenceFrom',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='posting',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postReference', to='wordle.references'),
        ),
        migrations.AddField(
            model_name='posting',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postWriter', to=settings.AUTH_USER_MODEL),
        ),
    ]
